# Enable C++ support
language: c
# Compiler selection
compiler:
 - clang
 - gcc
# Build steps
script:
 - mkdir build
 - cd build
 - cmake ../program_sources && make
addons:
  apt:
    sources:
     - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
     - cmake
     - cmake-data
