# Enable C++ support
language: c
# Compiler selection
compiler:
 - clang
 - gcc
# Build steps
script:
 - mkdir build
 - cd build
 - cmake ../program_sources && make
addons:
  apt:
    sources:
     - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
     - cmake
     - cmake-data
matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
    - env: CXX=g++-6 CC=gcc-6
    - env: CXX=clang++-3.8 CC=clang-3.8
