# I need these ones before working
addons:
  apt:
    sources:
     - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
     - cmake
     - cmake-data
# Enable C++ support
language: c
# Compiler selection
#compiler:
# - clang
# - gcc
# Esto creo que no lo voy a usar, y encima casca
#install: make get-deps
# Different versions for compilers
matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
    - env: CXX=g++-6 CC=gcc-6
    - env: CXX=clang++-3.8 CC=clang-3.8
# Build steps
script:
 - mkdir build
 - cd build
 - echo ${CC}
 - echo ${CXX}
 - cmake ../program_sources -DCMAKE_C_COMPILER=/usr/bin/${CC} -DCMAKE_CXX_COMPILER=/usr/bin/${CXX} && make
